/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Van-with-rear-door.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body001.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body002.geometry}
          material={materials.Body}
          position={[-1440.79, 2652.726, 933.315]}
          rotation={[0, 0, 1.306]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Driverside-Window"].geometry}
          material={materials.Glass}
          position={[-5.566, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lights.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Passangerside-window"].geometry}
          material={materials.Glass}
          position={[6.595, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires.geometry}
          material={materials.Tire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Windshield.geometry}
          material={materials.Glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body003.geometry}
        material={materials["Body.001"]}
      />
    </group>
  );
}

useGLTF.preload("/Van-with-rear-door.glb");

rembrandt;

city;
