/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { extend, useFrame } from "@react-three/fiber";
import React, { useRef, useState } from "react";
import { PivotControls, useGLTF } from "@react-three/drei";
import { editable as e } from "@theatre/r3f";

export function VanDoors(props) {
  const { nodes, materials } = useGLTF("/Van-with-rear-doors.glb");

  const meshRef = useRef();
  const [direction, setDirection] = useState(-1);
  const speedFactor = 350;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group ref={meshRef}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Driverside-Window"].geometry}
            material={materials.Glass}
            position={[-5.566, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Passangerside-window"].geometry}
            material={materials.Glass}
            position={[6.595, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body001.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lights.geometry}
          material={materials.Glass}
        />
        <group
          position={[230, 2660.285, 1160]}
          rotation={[Math.PI * -120, 0, 0]}
        >
          <e.group theatreKey="Left Rear Door">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Rear-Door-Left"].geometry}
              material={materials.Body}
              rotation={[0, 0, -18.81]}
            />
          </e.group>
        </group>
        <group
          position={[-1440.79, 2652.726, 933.315]}
          rotation={[Math.PI * -120, 0, 0]}
        >
          <e.group theatreKey="Right Rear Door">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Rear-Door-Right"].geometry}
              material={materials.Body}
              rotation={[0, 0, 18.83]}
            />
          </e.group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires.geometry}
          material={materials.Tire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Windshield.geometry}
          material={materials.Glass}
          material-transparent={true}
          material-opacity={0.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Van-with-rear-doors.glb");
