/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { extend } from "@react-three/fiber";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Van(props) {
  const { nodes, materials } = useGLTF("/Van.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body.geometry}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Tires.geometry}
              material={materials.Tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Windows.geometry}
              material={materials.Glass}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Van.glb");
